Create using_development_nuget_packages.md
MonoGame/docs.monogame.github.io pull request #62
Opened 2024-09-14 08:53 UTC by dellis1972

Add some documentation on how to use the GitHub NuGet Feed.

2024-09-14 14:10 UTC, dellis1972 commented
Don't merge this year. I want to double check it. I just flagged it for a review.

2024-09-14 17:59 UTC, dellis1972 commented
ok , should be good to go now

2024-09-14 18:44 UTC, SimonDarksideJ requested changes

2024-09-14 18:44 UTC, SimonDarksideJ commented on articles/getting_started/using_development_nuget_packages.md
> +# Using the Development Nuget Packages
Header needs the front matter used by the doc generator and remove the h1 element (it should be the title)

2024-09-14 18:44 UTC, SimonDarksideJ commented on articles/getting_started/using_development_nuget_packages.md
> +For more information, you can read [consuming-packages-authenticated-feeds](https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#credentials-in-nugetconfig-
Needs a trailing space for markdown spec

2024-09-14 18:44 UTC, SimonDarksideJ commented on articles/getting_started/using_development_nuget_packages.md
> +very latest code you can use this Feed to do that.
Can we also add a ;tldr breakdown list of steps to do

2024-09-26 21:57 UTC, SimonDarksideJ approved these changes

2024-09-29 08:35 UTC, merged